### ISSUE TITLE
Tag jmoiron/sqlx releases

### ISSUE THREAD

**Issue by maraino** [go-sqlx/sqlx#21]
### Description

To make the migration to go-sqlx easier, we should tag commits released by `jmoiron/sqlx`. 
The tagged releases are at https://github.com/jmoiron/sqlx/tags. The semver ones are reproduced here:

| Tag    | Commit  |
| ------ | ------- |
| v1.3.5 | 28212d4 |
| v1.3.4 | 92bfa36 |
| v1.3.3 | 874a5d4 |
| v1.3.2 | 1723f86 |
| v1.3.1 | 75a7ebf |
| v1.3.0 | 4cb7f7d |
| v1.2.0 | d161d7a |

**Comment by uvulpos** [comment]
Would you prefer to stay more stable or more current? We could either mark them manually, but we could also use tools like https://github.com/thenativeweb/get-next-version. What do you think / prefer?

**Comment by maraino** [comment]
At the moment, I would like to switch from `github.com/jmoiron/sqlx v1.3.5` to `github.com/go-sqlx/sqlx v1.3.5` using `go get github.com/go-sqlx/sqlx@v1.3.5` and "Find and Replace" in my code.

Later, when a `go-sqlx` gets a new release, [dependabot](https://github.com/dependabot) will send me a PR, it will run the unit tests, and if there are no issues, I can merge it and upgrade to v1.x.x.

At the moment, I only need the latest version, but I suppose there will be more people in a similar situation but with a lower version, so I think it is a good practice to add those 7 tags manually.

**Comment by maraino** [comment]
It should be as simple as running this for all the 7 versions:

```shell
git tag v1.2.0 d161d7a
git push origin v1.2.0
```

**Comment by uvulpos** [comment]
Should be done, can you test it?

**Comment by maraino** [comment]
:( I didn't realize that on those tags, the `go.mod` was still `github.com/jmoiron/sqlx`.

Doing a replacement, you're sure we're using this repo, but you still need to import `github.com/jmoiron/sqlx`:

```
module foo

go 1.21.0

require github.com/jmoiron/sqlx v1.3.5

replace github.com/jmoiron/sqlx => github.com/go-sqlx/sqlx v1.3.5
```

So not a great solution, I leave it up to you if you want to rollback this change or not.

**Comment by uvulpos** [comment]
To solve this issue, I created a new release v1.3.6

**Comment by uvulpos** [comment]
Please check again and let me know :)

**Comment by maraino** [comment]
That should be ok, for anyone concern these are the changes between last jmoiron release and this new one, https://github.com/go-sqlx/sqlx/compare/v1.3.5...v1.3.6
