### ISSUE TITLE
How to use NamedExec to call a Procedure?

### ISSUE THREAD

**Issue by huazhenhz** [go-sqlx/sqlx#26]
How to use NamedExec to call a Procedure, are there any examples or demo?
Thanks a lot!

**Comment by uvulpos** [comment]
Hi @huazhenhz,
in general: the original repo here has a documentation we did not clone and set up yet, but there is everything explained, we're just doing bug fixes: https://jmoiron.github.io/sqlx/#namedParams

**About your problem:**  
[See source code here](https://github.com/go-sqlx/sqlx/blob/a41d1d02a09aea12bf8fdecbe4a8f654d68b7fcb/named.go#L452): Sqlx is just a wrapper above from database/sql with some extra magic. Below there are basic sql database calls like you would expect based on the name. So what you can do is just google for solutions for the database/sql package, you don't have to specify sqlx in your search terms. Should work as well.

I searched your problem on Google and this might be the solution you are looking for: https://stackoverflow.com/a/73057614 🙂 

Please reach out to me, if this helps 👍🏻

**Comment by huazhenhz** [comment]
Maybe the NamedExec Function and NamedQuery Function of sqlx cannot support Procedures.
All the examples about the NamedExec Function and NamedQuery Function are used for the SQL Command Text Mode.

Many thanks for your reply!

**Comment by uvulpos** [comment]
Calling Procedures is at least not a that common use case. I would not rely on missing examples, but I don't know, have to check it later after work 🙂

**Comment by huazhenhz** [comment]
> Calling Procedures is at least not a that common use case. I would not rely on missing examples, but I don't know, have to check it later after work 🙂

Thank you for your help!
