### ISSUE TITLE
Implement MySQL Checks in CI Pipelines

### ISSUE THREAD

**Issue by uvulpos** [go-sqlx/sqlx#7]
Followup Issue:

While implementing the CI Pipeline, I was at some point not able to create a MySQL connection. It always said addr not found. The goal of the issue is to make it work.

**Comment by BenKnigge** [comment]
I'll take a look at this at some point this weekend.

**Comment by uvulpos** [comment]
> I'll take a look at this at some point this weekend.

Thanks a lot. I think it was probably something stupidly simple. Will also check into it.

**Comment by BenKnigge** [comment]
It was a struggle but It's working, feel free to make any improvement you think are necessary.

here's the pr

https://github.com/go-sqlx/sqlx/pull/10

**Comment by uvulpos** [comment]
done ✅
